Hunter6/src/Hunter/Controllers/AuthTestController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using Hunter.Security;

namespace Hunter.Controllers
{
    public class AuthTestController : Controller
    {
        private readonly IAuthorizationService authorizationService;

        public AuthTestController(IAuthorizationService authorizationService)
        {
            this.authorizationService = authorizationService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [Authorize(Policy = "RequireClimePolicyTest")]
        public IActionResult RequireClimePolicyTest()
        {
            return View();
        }

        [Authorize(Policy = "RequireRolePolicyTest")]
        public IActionResult RequireRolePolicyTest()
        {
            return View();
        }

        [Authorize(Policy = "RequirementBasedPolicyTest")]
        public IActionResult RequirementBasedPolicyTest()
        {
            return View();
        }

        public async Task<IActionResult> ResourceBasedPolicyTest()
        {
            var resource = new TestResource();

            if (!await authorizationService.AuthorizeAsync(User, resource, ResourceOperations.Read))
            {
                return new ChallengeResult();
            }

            return View();
        }
    }
}

Hunter6/src/Hunter/Views/AuthTest/Index.cshtml
<h2>Authorization test page</h2>

<p>This is the authorization test page. Please select one of the below options to test authorization:</p>
<ul>
    <li><a asp-controller="AuthTest" asp-action="RequireClimePolicyTest">Policy with a claim requirement test</a></li>
    <li><a asp-controller="AuthTest" asp-action="RequireRolePolicyTest">Policy with a role requirement test</a></li>
    <li><a asp-controller="AuthTest" asp-action="RequirementBasedPolicyTest">Policy with the requirement test</a></li>
    <li><a asp-controller="AuthTest" asp-action="ResourceBasedPolicyTest">Resource-based authorization test</a></li>
</ul>

Hunter6/src/Hunter/Views/AuthTest/RequireClimePolicyTest.cshtml
<h2>You have passed authorization because you have RequireClimePolicyTest claim</h2>
<a asp-controller="AuthTest" asp-action="Index">Go back</a>

Hunter6/src/Hunter/Views/AuthTest/RequireRolePolicyTest.cshtml
<h2>You have passed authorization because you have RequireRolePolicyTest role</h2>
<a asp-controller="AuthTest" asp-action="Index">Go back</a>

Hunter6/src/Hunter/Views/AuthTest/RequirementBasedPolicyTest.cshtml
<h2>You have passed authorization because TestRequirement was satisfied</h2>
<a asp-controller="AuthTest" asp-action="Index">Go back</a>

Hunter6/src/Hunter/Views/AuthTest/ResourceBasedPolicyTest.cshtml
<h2>You have passed authorization because you have TestResource read permissions</h2>
<a asp-controller="AuthTest" asp-action="Index">Go back</a>