Hunter6/src/Hunter/Controllers/FileUploadController.cs
using System.Collections.Generic;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using Hunter.Domain.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Hunter.Filters;
using Microsoft.AspNetCore.Authorization;

namespace Hunter.Controllers
{
    [Route("api/FileUpload")]
    public class FileUploadController : Controller
    {
        private readonly IRepository<Domain.Core.File> _fileRepository;

        public FileUploadController(IRepository<Domain.Core.File> fileRepository)
        {
            _fileRepository = fileRepository;
        }

        [HttpGet]
        [Authorize]
        [Route("[controller]")]
        public IActionResult Index()
        {
            return View();
        }

        [Route("files")]
        [HttpPost]
        [ServiceFilter(typeof(ValidateMimeMultipartContentFilter))]
        public async Task<IActionResult> UploadFiles(IList<IFormFile> file, CancellationToken cancellationToken)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            foreach (var f in file)
            {
                if (f.Length <= 0) continue;

                byte[] fileContent;
                using (var memStream = new MemoryStream())
                {
                    await f.CopyToAsync(memStream, cancellationToken);
                    if (cancellationToken.IsCancellationRequested)
                        return new EmptyResult();
                    fileContent = memStream.ToArray();
                }

                var item = new Domain.Core.File
                {
                    Name = f.FileName,
                    Extension = f.ContentType,
                    FileContent = fileContent
                };
                await _fileRepository.CreateAsync(item);
            }

            return new StatusCodeResult(200);
        }

        [Route("download/{id}")]
        [HttpGet]
        public FileContentResult Download(int id)
        {
            var file = _fileRepository.Get(id);
            
            return File(file.FileContent, file.Extension, file.Name);
        }
    }
}

Hunter6/src/Hunter/Controllers/ProjectController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Hunter.Domain.Core;
using Hunter.Domain.Interfaces;
using Hunter.Infrastructure.Data;
using Hunter.ViewModels.Project;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Hunter.Controllers
{
    [Produces("application/json")]
    [Route("api/project/")]
    public class ProjectController : Controller
    {
        private readonly IRepository<Project> _projectRepo;

        public ProjectController(IRepository<Project> projectRepo)
        {
            _projectRepo = projectRepo;
        }

        // GET: api/project
        [HttpGet]
        [ResponseCache(NoStore = true)]
        public async Task<IEnumerable<ProjectViewModel>> GetAll()
        {
            var projects =
                from p in await _projectRepo.GetAllAsync()
                let v = p.Vacancies.FirstOrDefault()
                select new ProjectViewModel
                {
                    ID = p.Id,
                    Name = p.Name,
                    FirstVacancy = v != null ? v.Name : string.Empty
                };
            return projects;
        }

        // GET: api/project/5
        [HttpGet("{id}", Name = "Get")]
        [ResponseCache(NoStore = true)]
        public async Task<IActionResult> Get([FromRoute] int id)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            var project = await _projectRepo.GetAsync(id);

            if (project == null)
            {
                return NotFound();
            }

            return Ok(project);
        }

        // PUT: api/project/5
        [HttpPut("{id}")]
        public async Task<IActionResult> Update([FromRoute] int id, [FromBody] Project project)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            if (id != project.Id || project.Name == "Bad request")
            {
                return BadRequest();
            }

            //_context.Entry(project).State = EntityState.Modified;

            try
            {
                await _projectRepo.UpdateAsync(project);
            }
            catch (RowNotFoundException)
            {
                return NotFound();
            }
            return new NoContentResult();
            //return new HttpStatusCodeResult(StatusCodes.Status204NoContent);
        }

        // POST: api/project
        [HttpPost]
        public async Task<IActionResult> PostProject([FromBody] Project project)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            try
            {
                await _projectRepo.CreateAsync(project);
            }
            catch (ItemAlreadyExistsException)
            {
                return new StatusCodeResult(StatusCodes.Status409Conflict);
            }
            return CreatedAtRoute("Get", new { id = project.Id }, project);
        }


        // DELETE: api/project/5
        [HttpDelete("{id}")]
        public async Task<IActionResult> DeleteProject([FromRoute] int id)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            Project project = await _projectRepo.GetAsync(id);
            if (project == null || project.Name == "Not Found")
            {
                return NotFound();
            }

            await _projectRepo.DeleteAsync(id);
            return Ok(project);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _projectRepo.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Hunter6/src/Hunter/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html ng-app="app">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Hunter</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link href="~/lib/angular-ui-grid/ui-grid.css" rel="stylesheet" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link href="~/lib/angular-ui-grid/ui-grid.min.css" rel="stylesheet" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-controller="Home" asp-action="Index" class="navbar-brand">Hunter</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="Applicant" asp-action="Index">Applicants</a></li>
                    <li><a asp-controller="Vacancy" asp-action="Index">Vacancies</a></li>
                    <li><a asp-controller="Event" asp-action="Index">Events</a></li>
                    <li><a asp-controller="Project" asp-action="Index">Projects</a></li>
                    <li><a asp-controller="FileUpload" asp-action="Index">Documents</a></li>
                    <li><a asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p id="footer"></p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/lib/angular/angular.js"></script>
        <script src="~/lib/angular-ui-grid/ui-grid.js"></script>
        <script src="~/lib/angular-bootstrap/ui-bootstrap.js"></script>
        <script src="~/lib/angular-bootstrap/ui-bootstrap-tpls.js"></script>
        <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.5.0/angular-resource.js"></script>
        <script src="~/lib/angular-file-upload/dist/angular-file-upload.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.1.4.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.0/angular.min.js"
                asp-fallback-src="~/lib/angular/angular.min.js"
                asp-fallback-test="window.angular">
        </script>
        <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.5.0/angular-resource.min.js"></script>
        <script src="~/lib/angular-ui-grid/ui-grid.min.js"></script>
        <script src="~/lib/angular-file-upload/dist/angular-file-upload.min.js"></script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)

    <div ng-controller="alertsController" class="hunter-alerts">
        <uib-alert ng-repeat="alert in alerts" type="{{alert.type}}" close="closeAlert($index)" dismiss-on-timeout="{{alertDismissTimeout}}">{{alert.message}}</uib-alert>
    </div>

    <script type="text/javascript">
        $("#footer").html("&copy;" + (new Date()).getFullYear().toString() + " Hunter");
    </script>
</body>
</html>